const { PrismaClient } = require('@prisma/client');
const { join, resolve } = require('path');
const log4js = require('log4js');

const { path } = require('./config.js');
const logger = log4js.getLogger();
logger.level = 'debug';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: `file:${join(resolve(path))}`,
    },
  },
});

logger.info(`checking db ${path}`);

const creators = [
  '282328724',
  '729kn',
  'a12311221',
  'Acce1erator',
  'Alois201111',
  'amanaOOSK',
  'arashi假面',
  'ArcadiaUtopia',
  'Astra2',
  'ayazuko',
  'banerjee',
  'Benzenick',
  'Benzenink',
  'bingliubzd123',
  'bv02468',
  'byslm',
  'ccyy111',
  'cfccvd1',
  'ChibaNils',
  'DD_orange',
  'eronolim',
  'ethane00',
  'falco20010124',
  'feiguh',
  'GKDorGCK',
  'Grolken',
  'HasturDelta',
  'HavocZeng',
  'hda15554435182',
  'hephaestus18',
  'homolivers364',
  'houda9918',
  'jinlin233xxx',
  'k45ooo',
  'Ken',
  'ken啊我',
  'LEGALID',
  'limakm',
  'LittleLemonTree',
  'Llamarider',
  'Lnco♂H',
  'luozijin999',
  'Mouchy',
  'NagatoSnake',
  'nameabcd',
  'Nils',
  'panaricelive',
  'paulla',
  'PlaneMans',
  'qefvb5',
  'raku2000',
  'schiiii',
  'Shizukuishi',
  'STROHEIM',
  'ststyst4399',
  'Takatoshi',
  'tu214R',
  'Tye_sine',
  'UID42134735',
  'UID63639877（RiverOfCrystals）',
  'voider000',
  'W_Sonoda',
  'wyymhjh',
  'ycgulie',
  'ymz2096133',
  'YOWANE',
  'yuejijnqi',
  'z1212cz',
  'z2566687',
  'zsber',
  '一张彩纸',
  '十六英寸的维包子',
  '八雲之青',
  '大白风',
  '万碎碎碎碎碎',
  '千綿奏',
  '女人的名字',
  '飞扬彤',
  '王城双基',
  '不愿意透露姓名的盒子精',
  '比那名居花花',
  '风之低吟',
  '心态已经爆炸了',
  '平酱今天好好休息了吗',
  '东方季枫',
  '东京水道水',
  '代号天狼ml',
  '弗洛伦斯的追随者',
  '托雷那为马娘所雷普歌',
  '亚历山大港的灯塔',
  '在相见之前先跳舞吧',
  '丢丢丢啪啪啪轰',
  '乔图姆乔斯达',
  '伏见泉水',
  '华生宇',
  '自我厌恶者',
  '安日云',
  '那谁谁是也',
  '红烟落城',
  '进击的南村群童',
  '赤炎',
  '还是狗带好了',
  '我真哒是个大活人',
  '我就是雷gay的化身',
  '肠胃不好的暴食者',
  '狂龙Kulo',
  '沉迷天使的猫',
  '快速逃走的熊',
  '鸡盒王yww',
  '驱逐舰最棒了',
  '非洲超级大咸鱼',
  '狐谈风月',
  '夜狐竹笋',
  '指一本',
  '南极洲老土著',
  '面壁の滑稽',
  '鬼道111',
  '洛缇lt',
  '恒守敬之',
  '神奇东出真神奇',
  '陨落赤炎',
  '盈盈星尘',
  '盈盈星辰',
  '起啥不是个名字',
  '莫名的不知火',
  '哥布林祭祀',
  '射镇英雄',
  '凌晨两点半の雨',
  '被炉熊',
  '假面骑士金币',
  '渊歌',
  '祸鬼眷恋的神官',
  '琭琭如玉，珞珞如石',
  '提里奥·屠鸡者',
  '斯哥德克斯',
  '最后的副歌',
  '最低文化限度',
  '景飒1',
  '黑羽仙洛',
  '微软必应',
  '滚爬菌',
  '群星知心',
  '蔚蓝之空s',
  '睿智的（）',
  '橙の高兴',
  '魔神皇帝十六夜咲夜',
  '霸歌长吟',
];

async function task() {
  for (const someone of creators) {
    const count = await prisma.article.count({
      where: {
        OR: [
          {
            translator: someone,
          },
          {
            author: someone,
            translator: '',
          },
        ],
      },
    });
    if (count) {
      logger.info(someone);
    }
  }
  await prisma.$disconnect();
}

task().then(async () => {
  logger.info('task done!');
});
